In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [4]:
df = pd.DataFrame(pd.read_excel('334data.xlsx')) 
df.head()

,Part ID,Planning Leadtime,Order Policy,Order Point,Safety Stock Qty,Fixed Order Qty,Days Of Supply,Minimum Order Qty,Maximum Order Qty,Multiple Order Qty,...,Yr2011,Yr2012,Yr2013,Yr2014,Turns30,Demand 30day,Turns60,Demand 60day,Turns90,Demand 90day
0,3.290050e+09,21,P,NaN,2400.0,NaN,28.0,2400.0,NaN,2400.0,...,240104.0,118284.0,119960.0,204486.00,15.940000,19128.00,7.886667,18928.0,0.000000,0.00
1,3.290400e+09,90,P,NaN,5400.0,NaN,28.0,NaN,NaN,540.0,...,108576.0,81707.0,109442.0,27938.00,13.241128,7276.00,6.511374,7156.0,0.000000,0.00
2,3.271255e+09,42,P,NaN,NaN,NaN,30.0,12960.0,NaN,432.0,...,79033.0,121980.0,50539.0,62167.22,25.981835,13313.85,0.421522,432.0,2.701134,4152.42
3,3.290051e+09,21,P,NaN,4800.0,NaN,30.0,4800.0,NaN,4800.0,...,NaN,NaN,NaN,NaN,19.990000,7996.00,4.370000,3496.0,6.913333,8296.00
4,3.265400e+09,21,N,2000.0,NaN,NaN,NaN,8000.0,NaN,1000.0,...,51000.0,57000.0,36000.0,36000.00,99999.000000,1.00,99999.000000,1.0,99999.000000,0.00

In [5]:
# Calculating the percentage of missing values in each column
missing_percentage = (df.isnull().sum() / len(df)) * 100

# Filtering out the percentages for the relevant columns identified for forecasting
relevant_columns = [
    'Yr2000', 'Yr2001', 'Yr2002', 'Yr2003', 'Yr2004', 'Yr2005', 'Yr2006', 
    'Yr2007', 'Yr2008', 'Yr2009', 'Yr2010', 'Yr2011', 'Yr2012', 'Yr2013', 'Yr2014',
    'Qty On Hand', 'Qty Available Mrp', 'Planning Leadtime', 'Purc Lt',
    'Minimum Order Qty', 'Maximum Order Qty', 'Multiple Order Qty',
    'Safety Stock Qty', 'Fixed Order Qty', 'Annual Usage Qty', 'Prev Yr Usage',
    'Roll Ann Usage', 'Turns30', 'Demand 30day', 'Turns60', 'Demand 60day',
    'Turns90', 'Demand 90day', 'Mean', 'Stddev', 'Coeff'
]

missing_percentage_relevant = missing_percentage[relevant_columns]
missing_percentage_relevant

Yr2000                  3.259475
Yr2001                  3.259475
Yr2002                  3.259475
Yr2003                  3.259475
Yr2004                  3.259475
Yr2005                  3.259475
Yr2006                 93.362937
Yr2007                 93.638914
Yr2008                 89.040442
Yr2009                 89.492453
Yr2010                 87.828645
Yr2011                 88.739481
Yr2012                 88.941636
Yr2013                 89.184677
Yr2014                 90.076206
Qty On Hand             0.000000
Qty Available Mrp       0.000000
Planning Leadtime       0.000000
Purc Lt                27.849769
Minimum Order Qty      69.213297
Maximum Order Qty      89.336862
Multiple Order Qty     26.159839
Safety Stock Qty       94.605399
Fixed Order Qty        33.294341
Annual Usage Qty        0.000000
Prev Yr Usage           0.498575
Roll Ann Usage          0.000000
Turns30                 0.000000
Demand 30day            0.000000
Turns60                 0.000000
Demand 60day            0.000000
Turns90                 0.000000
Demand 90day            0.000000
Mean                  100.000000
Stddev                100.000000
Coeff                 100.000000
dtype: float64