# Data Preprocessing

In [14]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.DataFrame(pd.read_excel('334data2.xlsx')) 
df.head()

,Part ID,Planning Leadtime,Order Policy,Order Point,Safety Stock Qty,Fixed Order Qty,Days Of Supply,Minimum Order Qty,Maximum Order Qty,Multiple Order Qty,...,2019-06-01 00:00:00,2019-07-01 00:00:00,2019-08-01 00:00:00,2019-09-01 00:00:00,2019-10-01 00:00:00,2019-11-01 00:00:00,2019-12-01 00:00:00,Annual 1,Annual 2,ANNUAL DEMAND
0,1.548500e+05,14,P,NaN,0.0,NaN,30.0,50.0,NaN,NaN,...,7.0,7.0,6.0,6.0,6.0,6.0,6.0,74.0,74.0,74.0
1,3.684600e+06,35,D,NaN,5.0,NaN,NaN,NaN,NaN,5.0,...,10.0,4.0,10.0,11.0,11.0,11.0,11.0,118.0,118.0,118.0
2,3.270501e+09,56,P,NaN,NaN,NaN,30.0,25.0,NaN,25.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,57.0,57.0,57.0
3,3.270820e+09,35,P,NaN,NaN,NaN,60.0,NaN,NaN,NaN,...,5.0,4.0,5.0,6.0,5.0,5.0,5.0,57.0,58.0,58.0
4,3.275500e+09,49,P,NaN,NaN,NaN,28.0,12.0,NaN,1.0,...,5.0,5.0,4.0,4.0,4.0,4.0,4.0,52.0,52.0,52.0

In [11]:
print('There are ', len(df), ' rows of data.')

There are  689  rows of data.